version: '3.8'

services:
  # MariaDB Database (lighter than MySQL)
  database:
    image: mariadb:10.11
    container_name: artyz_database
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: artyz_db
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_USER: artyz_user
      MARIADB_PASSWORD: artyz_password
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 3
      interval: 10s
      start_period: 20s
    networks:
      - artyz_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: artyz_backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_NAME=Artyz
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=artyz_db
      - DB_USERNAME=artyz_user
      - DB_PASSWORD=artyz_password
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      timeout: 10s
      retries: 3
      interval: 30s
      start_period: 40s
    networks:
      - artyz_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: artyz_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000/api
      - GENERATE_SOURCEMAP=false
    depends_on:
      - backend
    networks:
      - artyz_network

volumes:
  mariadb_data:

networks:
  artyz_network:
    driver: bridge