version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: artyz_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: artyz_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: artyz_user
      MYSQL_PASSWORD: artyz_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - artyz_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: artyz_backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - APP_NAME=Artyz
      - APP_ENV=local
      - APP_KEY=base64:your-32-character-secret-key-here
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=artyz_db
      - DB_USERNAME=artyz_user
      - DB_PASSWORD=artyz_password
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - artyz_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: artyz_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000/api
      - GENERATE_SOURCEMAP=false
    depends_on:
      - backend
    networks:
      - artyz_network

volumes:
  mysql_data:

networks:
  artyz_network:
    driver: bridge